version: "3.6"
services: 
    graphql-engine:
        image: hasura/graphql-engine:v1.3.1
        container_name: lit-hasura
        restart: always
        ports:
            - "${HASURA_GRAPHQL_PORT}:8080"
        # depends_on:
        #     - "postgres"
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${PG_PASSWORD}@postgres:${PG_PORT}/${PG_DB_NAME}
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            ## uncomment next line to set an admin secret
            HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
            HASURA_GRAPHQL_JWT_SECRET: "${HASURA_GRAPHQL_JWT_SECRET}"
            HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous